# Generated by Django 2.2.5 on 2022-03-25 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_goodsvisitcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='skuimage',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
    ]
